[[plugins]]
    package = "netlify-plugin-visual-diff"
    [plugins.inputs]
        serverUrl = "https://eyesapi.applitools.com" # The public Eyes server
        ignoreSelector = "" # There is no null in TOML, but if there were, then it would be null
        failBuildOnDiff = true 
        concurrency = 1
        [[plugins.inputs.browser]]
            name = "chrome"
            width = 1024
            height = 768

        [[plugins.inputs.browser]]
            name = "firefox"
            width = 1920
            height = 1080

        [[plugins.inputs.browser]]
            deviceName = "iPhone X"